# Generated by Django 2.1 on 2019-01-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_solving'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pe_query',
            field=models.TextField(default=''),
        ),
    ]
